export const ADD_BOOK = 'ADD_BOOK';
export const GET_BOOK_LIST = 'GET_BOOK_LIST';
export const EDIT_BOOK_ITEM = 'EDIT_BOOK_ITEM';
export const SEARCH_BOOK = 'SEARCH_BOOK';
export const SHOW_ADD_FORM = 'SHOW_ADD_FORM';
export const SHOW_UPDATE_FORM = 'SHOW_UPDATE_FORM';
export const UPDATE_BOOK_ITEM="UPDATE_BOOK_ITEM";
export const SET_UPDATE_ITEM="SET_UPDATE_ITEM";
export const FETCH_BOOK_LIST="FETCH_BOOK_LIST";